//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcakBiletiAlma.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UcakBiletiEntities : DbContext
    {
        public UcakBiletiEntities()
            : base("name=UcakBiletiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblHavalimani> tblHavalimanis { get; set; }
        public virtual DbSet<tblOnay> tblOnays { get; set; }
        public virtual DbSet<tblRezerve> tblRezerves { get; set; }
        public virtual DbSet<tblSinif> tblSinifs { get; set; }
        public virtual DbSet<tblUcret> tblUcrets { get; set; }
        public virtual DbSet<UcusKodu> UcusKodus { get; set; }
    }
}
