//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcakBiletiAlma.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHavalimani
    {
        public int il_no { get; set; }
        public string havalimaniAdi { get; set; }
    }
}
