//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcakBiletiAlma.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRezerve
    {
        public int RezerveId { get; set; }
        public string Nereden { get; set; }
        public string Nereye { get; set; }
        public Nullable<System.DateTime> GidisTarihi { get; set; }
        public Nullable<System.DateTime> DonusTarihi { get; set; }
        public Nullable<int> SaatId { get; set; }
        public string MusAdiSoyadi { get; set; }
        public string Tel { get; set; }
        public string TcNo { get; set; }
        public string Cinsiyet { get; set; }
        public string Email { get; set; }
        public Nullable<int> SinifId { get; set; }
        public string KoltukNo { get; set; }
        public Nullable<System.DateTime> DogumTarih { get; set; }
        public Nullable<int> UcretId { get; set; }
    
        public virtual tblSinif tblSinif { get; set; }
    }
}
