//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcakBiletiAlma.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUcret
    {
        public int Id { get; set; }
        public string Ucret { get; set; }
        public Nullable<int> SinifId { get; set; }
    
        public virtual tblSinif tblSinif { get; set; }
    }
}
