//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcakBiletiAlma.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UcusKodu
    {
        public int UcusId { get; set; }
        public string UcusKodu1 { get; set; }
        public Nullable<int> KalkisHavId { get; set; }
        public Nullable<System.TimeSpan> KalkisSaat { get; set; }
        public Nullable<int> VarisHavId { get; set; }
        public Nullable<System.TimeSpan> VarisSaat { get; set; }
        public Nullable<System.DateTime> KalkisTarih { get; set; }
        public Nullable<System.DateTime> VarisTarih { get; set; }
    }
}
